/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLHelloworldHelloGreeting.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   helloworld/v1
// Description:
//   This is an API
// Classes:
//   GTLHelloworldHelloGreeting (0 custom class methods, 1 custom properties)

#import "GTLHelloworldHelloGreeting.h"

// ----------------------------------------------------------------------------
//
//   GTLHelloworldHelloGreeting
//

@implementation GTLHelloworldHelloGreeting
@dynamic message;
@end
