/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLHelloworldConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   helloworld/v1
// Description:
//   This is an API

#import "GTLHelloworldConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeHelloworldUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
