/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLHelloworld_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   helloworld/v1
// Description:
//   This is an API

#import "GTLHelloworldConstants.m"

#import "GTLHelloworldHelloGreeting.m"
#import "GTLHelloworldHelloGreetingCollection.m"

#import "GTLQueryHelloworld.m"
#import "GTLServiceHelloworld.m"
