/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLHelloworldHelloGreeting.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   helloworld/v1
// Description:
//   This is an API
// Classes:
//   GTLHelloworldHelloGreeting (0 custom class methods, 1 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLHelloworldHelloGreeting
//

@interface GTLHelloworldHelloGreeting : GTLObject
@property (copy) NSString *message;
@end
