/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLHelloworld.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   helloworld/v1
// Description:
//   This is an API

#import "GTLHelloworldConstants.h"

#import "GTLHelloworldHelloGreeting.h"
#import "GTLHelloworldHelloGreetingCollection.h"

#import "GTLQueryHelloworld.h"
#import "GTLServiceHelloworld.h"
