/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLQueryHelloworld.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   helloworld/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryHelloworld (4 custom class methods, 3 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLHelloworldHelloGreeting;

@interface GTLQueryHelloworld : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (assign) NSInteger identifier;
@property (assign) NSInteger times;

#pragma mark -
#pragma mark "greetings" methods
// These create a GTLQueryHelloworld object.

// Method: helloworld.greetings.authed
//  Authorization scope(s):
//   kGTLAuthScopeHelloworldUserinfoEmail
// Fetches a GTLHelloworldHelloGreeting.
+ (id)queryForGreetingsAuthed;

// Method: helloworld.greetings.getGreeting
//  Authorization scope(s):
//   kGTLAuthScopeHelloworldUserinfoEmail
// Fetches a GTLHelloworldHelloGreeting.
+ (id)queryForGreetingsGetGreetingWithIdentifier:(NSInteger)identifier;

// Method: helloworld.greetings.listGreeting
//  Authorization scope(s):
//   kGTLAuthScopeHelloworldUserinfoEmail
// Fetches a GTLHelloworldHelloGreetingCollection.
+ (id)queryForGreetingsListGreeting;

// Method: helloworld.greetings.multiply
//  Authorization scope(s):
//   kGTLAuthScopeHelloworldUserinfoEmail
// Fetches a GTLHelloworldHelloGreeting.
+ (id)queryForGreetingsMultiplyWithObject:(GTLHelloworldHelloGreeting *)object
                                    times:(NSInteger)times;

@end
